# Generated by Django 4.0.1 on 2022-01-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('LocationId', models.AutoField(primary_key=True, serialize=False)),
                ('LocationName', models.CharField(max_length=500)),
                ('LocationsDescription', models.CharField(max_length=500)),
                ('LocationsGPS', models.CharField(max_length=500)),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('ReviewId', models.AutoField(primary_key=True, serialize=False)),
                ('ReviewContent', models.CharField(max_length=500)),
                ('ReviewDate', models.DateField()),
                ('ReviewRating', models.IntegerField()),
                ('Traveller', models.CharField(max_length=500)),
                ('Location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Travellers',
            fields=[
                ('TravellerId', models.AutoField(primary_key=True, serialize=False)),
                ('TravellerFirstName', models.CharField(max_length=500)),
                ('TravellerLastName', models.CharField(max_length=500)),
            ],
        ),
    ]
