# Generated by Django 4.0.1 on 2022-01-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travellers',
            name='TravellerBio',
            field=models.CharField(default='', max_length=500),
        ),
    ]
