# Generated by Django 4.0.1 on 2022-01-22 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TravelApp', '0002_travellers_travellerbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TravelApp.locations'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Traveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TravelApp.travellers'),
        ),
    ]
